# Generated by Django 4.2.5 on 2023-09-26 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0015_produtostags_tag_id'),
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProaqDadosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('unidade_daf', models.TextField(choices=[('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE'), ('nao_informado', 'Não Informado')], max_length=15)),
                ('modalidade_aquisicao', models.TextField(max_length=30)),
                ('numero_processo_sei', models.TextField(max_length=20)),
                ('numero_etp', models.TextField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='nao_informado', max_length=20)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_deletado', to='usuarios.usuario')),
                ('denominacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacao_proaq', to='produtos.denominacoesgenericas')),
                ('responsavel_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_responsavel', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_registro', to='usuarios.usuario')),
            ],
        ),
    ]
