# Generated by Django 4.2.5 on 2023-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqdadosgerais',
            name='modalidade_aquisicao',
            field=models.TextField(choices=[('inexigibilidade', 'Emergencial'), ('emergencial', 'Inexigibilidade'), ('pregao_comarp', 'Pregão Com ARP'), ('pregao_semarp', 'Pregão Sem ARP')], max_length=30),
        ),
    ]
