# Generated by Django 4.2.5 on 2023-10-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('produtos', '0015_produtostags_tag_id'),
        ('processos_aquisitivos', '0002_alter_proaqdadosgerais_modalidade_aquisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqdadosgerais',
            name='modalidade_aquisicao',
            field=models.TextField(choices=[('emergencial', 'Emergencial'), ('inexigibilidade', 'Inexigibilidade'), ('pregao_comarp', 'Pregão Com ARP'), ('pregao_semarp', 'Pregão Sem ARP')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProaqProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_proaqproduto_deletado', to='usuarios.usuario')),
                ('proaq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_produto', to='processos_aquisitivos.proaqdadosgerais')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_proaq', to='produtos.produtosfarmaceuticos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_proaqproduto', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_proaqproduto', to='usuarios.usuario')),
            ],
        ),
    ]
