# Generated by Django 4.2.5 on 2023-10-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('processos_aquisitivos', '0003_alter_proaqdadosgerais_modalidade_aquisicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProaqEvolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('fase', models.IntegerField()),
                ('status', models.TextField(choices=[('executado', 'Executado'), ('em_execucao', 'Em Execução'), ('nao_executado', 'Não Executado')], max_length=15)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(default='Sem comentário.')),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_proaqevolucao_deletado', to='usuarios.usuario')),
                ('proaq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_evolucao', to='processos_aquisitivos.proaqdadosgerais')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_proaqevolucao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_proaqevolucao', to='usuarios.usuario')),
            ],
        ),
    ]
