# Generated by Django 4.2.5 on 2023-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0004_proaqevolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqevolucao',
            name='status',
            field=models.TextField(choices=[('em_execucao', 'Em Execução'), ('nao_executado', 'Não Executado'), ('executado', 'Executado')], max_length=15),
        ),
    ]
