# Generated by Django 4.2.5 on 2023-10-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0006_alter_proaqevolucao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqevolucao',
            name='status',
            field=models.TextField(choices=[('nao_executado', 'Não Executado'), ('executado', 'Executado'), ('em_execucao', 'Em Execução')], max_length=15),
        ),
    ]
