# Generated by Django 4.2.5 on 2023-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0007_alter_proaqevolucao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proaqevolucao',
            name='status',
            field=models.TextField(choices=[('executado', 'Executado'), ('em_execucao', 'Em Execução'), ('nao_executado', 'Não Executado')], max_length=15),
        ),
    ]
