# Generated by Django 4.2.5 on 2023-10-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_aquisitivos', '0012_alter_proaqevolucao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROAQ_AREA_MS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=40)),
                ('orgao_publico', models.BooleanField()),
                ('ministerio', models.CharField(max_length=100)),
                ('secretaria', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PROAQ_ETAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=200)),
            ],
        ),
    ]
