# Generated by Django 4.2.5 on 2023-10-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('processos_aquisitivos', '0014_alter_proaq_area_ms_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProaqTramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('documento_sei', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=50)),
                ('etapa_processo', models.CharField(max_length=100)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('previsao_saida', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(default='Sem observações.')),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_proaqtramitacao_deletado', to='usuarios.usuario')),
                ('proaq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proaq_tramitacao', to='processos_aquisitivos.proaqdadosgerais')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_proaqtramitacao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_proaqtramitacao', to='usuarios.usuario')),
            ],
        ),
    ]
