# Generated by Django 4.2.5 on 2023-09-09 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_alocacao_unidade_alter_alocacao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominacoesGenericas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('denominacao', models.CharField(max_length=140)),
                ('tipo_produto', models.CharField(blank=True, choices=[('insumo', 'Insumo'), ('medicamento', 'Medicamento'), ('nao_informado', 'Não Informado')], max_length=15, null=True)),
                ('unidade_basico', models.BooleanField(db_index=True, default=False)),
                ('unidade_especializado', models.BooleanField(db_index=True, default=False)),
                ('unidade_estrategico', models.BooleanField(db_index=True, default=False)),
                ('unidade_farm_popular', models.BooleanField(db_index=True, default=False)),
                ('hospitalar', models.BooleanField(db_index=True, default=False)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacoes_editadas', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacoes_registradas', to='usuarios.usuario')),
            ],
        ),
    ]
