# Generated by Django 4.2.5 on 2023-09-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_denominacoesgenericas_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='denominacoesgenericas',
            name='log_n_edicoes',
            field=models.IntegerField(default=1),
        ),
    ]
