# Generated by Django 4.2.5 on 2023-09-14 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('produtos', '0005_remove_denominacoesgenericas_del_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosFarmaceuticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('produto', models.CharField(max_length=240)),
                ('concentracao_tipo', models.CharField(choices=[('nao_se_aplica', 'Não se aplica'), ('nao_informado', 'Não Informado'), ('mostrar_nao', 'Não mostrar'), ('mostrar_nome', 'Mostrar')], max_length=20)),
                ('concentracao', models.CharField(max_length=120)),
                ('forma_farmaceutica', models.CharField(choices=[('capsula', 'Cápsula'), ('granulado_oral', 'Granulado Oral'), ('seringa_preenchida', 'Seringa Preenchida'), ('suspensao_oral', 'Suspensão Oral'), ('suspensao_injetavel', 'Suspenção Injetável'), ('comprimido_mastigavel', 'Comprimido Mastigável'), ('capsula_mole', 'Cápsula Mole'), ('solucao_oral', 'Solução Oral'), ('goma_mascar', 'Goma de Mascar'), ('pastilha', 'Pastilha'), ('po_solucao_injetavel', 'Pó para Solução Injetável'), ('nao_informado', 'Não Informado'), ('seringa_injetavel', 'Solução Injetável'), ('gel', 'Gel'), ('comprimido_lib_prolongada', 'Comprimido de Liberação Prolongada'), ('comprimido_dispersivel', 'Comprimido Dispersível'), ('comprimido', 'Comprimido'), ('xarope', 'Xarope'), ('adesivo_transdermico', 'Adesivo Transdérmico')], max_length=60)),
                ('oncologico', models.BooleanField(default=False)),
                ('biologico', models.BooleanField(default=False)),
                ('aware', models.CharField(max_length=20)),
                ('incorp_status', models.CharField(choices=[('incorporado', 'Incorporado'), ('excluido', 'Excluído'), ('nao_informado', 'Não Informado')], max_length=20)),
                ('incorp_data', models.DateField(blank=True, null=True)),
                ('incorp_portaria', models.CharField(max_length=30)),
                ('incorp_link', models.URLField(max_length=100)),
                ('exclusao_data', models.DateField(blank=True, null=True)),
                ('exclusao_portaria', models.CharField(max_length=30)),
                ('exclusao_link', models.URLField(max_length=100)),
                ('comp_basico', models.BooleanField(default=False)),
                ('comp_especializado', models.BooleanField(default=False)),
                ('comp_estrategico', models.BooleanField(default=False)),
                ('comp_basico_programa', models.CharField(max_length=60, null=True)),
                ('comp_especializado_grupo', models.CharField(max_length=60, null=True)),
                ('comp_estrategico_programa', models.CharField(max_length=60, null=True)),
                ('sigtap_possui', models.BooleanField(default=False)),
                ('sigtap_codigo', models.CharField(max_length=10, null=True)),
                ('sigtap_nome', models.CharField(max_length=60, null=True)),
                ('sismat_possui', models.BooleanField(default=False)),
                ('sismat_codigo', models.CharField(max_length=10, null=True)),
                ('sismat_nome', models.CharField(max_length=60, null=True)),
                ('catmat_possui', models.BooleanField(default=False)),
                ('catmat_codigo', models.CharField(max_length=10, null=True)),
                ('catmat_nome', models.CharField(max_length=60, null=True)),
                ('obm_possui', models.BooleanField(default=False)),
                ('obm_codigo', models.CharField(max_length=10, null=True)),
                ('obm_nome', models.CharField(max_length=60, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_produto_deletado', to='usuarios.usuario')),
                ('denominacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacao_produto', to='produtos.denominacoesgenericas')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_produto', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_registro_produto', to='usuarios.usuario')),
            ],
        ),
    ]
