# Generated by Django 4.2.5 on 2023-09-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtosfarmaceuticos_concentracao_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='produtosfarmaceuticos',
            name='disp_farmacia_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtosfarmaceuticos',
            name='hospitalar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='aware',
            field=models.CharField(choices=[('acesso', 'Acesso'), ('alerta', 'Alerta'), ('reservado', 'Reservado'), ('nao_se_aplica', 'Não se aplica'), ('nao_informado', 'Não Informado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='concentracao_tipo',
            field=models.CharField(choices=[('mostrar_nome', 'Mostrar no nome'), ('mostrar_nao', 'Não mostrar'), ('nao_se_aplica', 'Não se aplica'), ('nao_informado', 'Não Informado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('adesivo_transdermico', 'Adesivo Transdérmico'), ('capsula', 'Cápsula'), ('capsula_mole', 'Cápsula Mole'), ('comprimido', 'Comprimido'), ('comprimido_lib_prolongada', 'Comprimido de Liberação Prolongada'), ('comprimido_dispersivel', 'Comprimido Dispersível'), ('comprimido_mastigavel', 'Comprimido Mastigável'), ('gel', 'Gel'), ('goma_mascar', 'Goma de Mascar'), ('granulado_oral', 'Granulado Oral'), ('pastilha', 'Pastilha'), ('po_solucao_injetavel', 'Pó para Solução Injetável'), ('seringa_preenchida', 'Seringa Preenchida'), ('seringa_injetavel', 'Solução Injetável'), ('solucao_oral', 'Solução Oral'), ('suspensao_injetavel', 'Suspenção Injetável'), ('suspensao_oral', 'Suspensão Oral'), ('xarope', 'Xarope'), ('nao_informado', 'Não Informado')], max_length=60),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='incorp_status',
            field=models.CharField(choices=[('incorporado', 'Incorporado'), ('excluido', 'Excluído'), ('nao_informado', 'Não Informado')], max_length=20),
        ),
    ]
