# Generated by Django 4.2.5 on 2023-09-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_tagprodutos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosfarmaceuticos',
            name='comp_basico_programa',
        ),
        migrations.RemoveField(
            model_name='produtosfarmaceuticos',
            name='comp_especializado_grupo',
        ),
        migrations.RemoveField(
            model_name='produtosfarmaceuticos',
            name='comp_estrategico_programa',
        ),
    ]
