# Generated by Django 4.2.5 on 2023-09-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_remove_produtosfarmaceuticos_comp_basico_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaATC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='produtosfarmaceuticos',
            name='atc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='aware',
            field=models.CharField(blank=True, choices=[('acesso', 'Acesso'), ('alerta', 'Alerta'), ('reservado', 'Reservado'), ('nao_se_aplica', 'Não se aplica'), ('nao_informado', 'Não Informado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='biologico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='catmat_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='catmat_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='catmat_possui',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='comp_basico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='comp_especializado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='comp_estrategico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='disp_farmacia_popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='exclusao_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='exclusao_portaria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='hospitalar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='incorp_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='incorp_portaria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='incorp_status',
            field=models.CharField(blank=True, choices=[('incorporado', 'Incorporado'), ('excluido', 'Excluído'), ('nao_informado', 'Não Informado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='obm_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='obm_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='obm_possui',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='oncologico',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sigtap_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sigtap_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sigtap_possui',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sismat_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sismat_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='sismat_possui',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
