# Generated by Django 4.2.5 on 2023-09-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_listaatc_produtosfarmaceuticos_atc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosfarmaceuticos',
            name='atc_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
