# Generated by Django 4.2.5 on 2023-09-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_produtostags_del_data_produtostags_del_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtostags',
            name='tag_id',
            field=models.IntegerField(default=None),
        ),
    ]
