# Generated by Django 4.2.5 on 2023-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produtostags_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='atc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
