# Generated by Django 4.2.5 on 2023-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_alter_produtosfarmaceuticos_atc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosfarmaceuticos',
            name='concentracao',
            field=models.CharField(max_length=240),
        ),
    ]
