# Generated by Django 4.2.5 on 2023-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_produtoconsumomedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoconsumomedio',
            name='aprovado_total',
            field=models.FloatField(default=0),
        ),
    ]
