# Generated by Django 4.2.5 on 2024-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urts',
            name='periodo_chuva_fim',
            field=models.IntegerField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_chuva_inicio',
            field=models.IntegerField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_seca_fim',
            field=models.IntegerField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_seca_inicio',
            field=models.IntegerField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True),
        ),
    ]
