# Generated by Django 4.2.5 on 2023-12-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_alocacoes_unidade'),
        ('urts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urts',
            old_name='proprietario',
            new_name='proprietario_nome',
        ),
        migrations.AddField(
            model_name='urts',
            name='proprietario_email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='urts',
            name='proprietario_telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_chuva_fim',
            field=models.ImageField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_chuva_inicio',
            field=models.ImageField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_seca_fim',
            field=models.ImageField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='urts',
            name='periodo_seca_inicio',
            field=models.ImageField(blank=True, choices=[('', ''), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='urts',
            name='textura_solo',
            field=models.CharField(blank=True, choices=[('', ''), ('arenoso', 'Arenoso'), ('argiloso_arenoso', 'Argiloso/Arenoso'), ('argiloso', 'Argiloso'), ('muito_argiloso', 'Muito Argiloso')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='URTespecieVegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('especie_vegetal', models.CharField(blank=True, max_length=120, null=True)),
                ('variedades', models.TextField(blank=True, null=True)),
                ('area_utilizada', models.CharField(blank=True, max_length=120, null=True)),
                ('producao_silagem', models.BooleanField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_vegetal_deletado', to='usuarios.usuarios')),
                ('urt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='urt_especie_vegetal', to='urts.urts')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_vegetal_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_vegetal_registro', to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='URTespecieAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('especie_animal', models.CharField(blank=True, max_length=120, null=True)),
                ('racas', models.TextField(blank=True, null=True)),
                ('area_utilizada', models.CharField(blank=True, max_length=120, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_animal_deletado', to='usuarios.usuarios')),
                ('urt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='urt_especie_animal', to='urts.urts')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_animal_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_urt_animal_registro', to='usuarios.usuarios')),
            ],
        ),
    ]
