# Generated by Django 4.2.5 on 2024-01-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0002_alter_urts_periodo_chuva_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urtespecievegetal',
            name='area_utilizada',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
