# Generated by Django 4.2.5 on 2023-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0002_rename_proprietario_urts_proprietario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urts',
            name='proprietario_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='urtespecieanimal',
            name='especie_animal',
            field=models.CharField(blank=True, choices=[('', ''), ('ovinos', 'Ovino'), ('bovino_corte', 'Bovino de Corte'), ('bovino_leite', 'Bovino de Leite')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='urtespecievegetal',
            name='especie_vegetal',
            field=models.CharField(blank=True, choices=[('', ''), ('cactaceas', 'Cactáceas'), ('gramineas_anuais', 'Gramíneas Anuais'), ('gramineas_perenes', 'Gramíneas Perenes')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='urts',
            name='local_preparo_amostras',
            field=models.CharField(blank=True, choices=[('', ''), ('area_experimento', 'Área do Experimento'), ('sede', 'Sede')], max_length=120, null=True),
        ),
    ]
