# Generated by Django 4.2.5 on 2024-02-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0002_ciclo_cicloperiodosclimaticos_cicloespeciesvegetais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='fase1',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='fase2',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='fase3',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase1_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase1_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase2_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase2_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase3_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='fase3_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
