# Generated by Django 4.2.5 on 2024-02-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('urts', '0003_remove_ciclo_fase1_remove_ciclo_fase2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEspeciesVegetaisAnimais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('tipo_especie', models.CharField(choices=[('animal', 'Animal'), ('vegetal', 'Vegetal')], max_length=30)),
                ('especie_vegetal', models.CharField(blank=True, choices=[('', ''), ('cactaceas', 'Cactáceas'), ('gramineas_anuais', 'Gramíneas Anuais'), ('gramineas_perenes', 'Gramíneas Perenes')], max_length=140, null=True)),
                ('variedades', models.CharField(blank=True, max_length=140, null=True)),
                ('area_utilizada', models.FloatField(blank=True, default=0, null=True)),
                ('producao_silagem', models.BooleanField(blank=True, null=True)),
                ('especie_animal', models.CharField(choices=[('', ''), ('ovinos', 'Ovino'), ('bovino_corte', 'Bovino de Corte'), ('bovino_leite', 'Bovino de Leite')], max_length=140)),
                ('racas', models.CharField(blank=True, max_length=140, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciclo_especie', to='urts.ciclo')),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_ciclo_especie_deletado', to='usuarios.usuarios')),
                ('urt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='urt_ciclo_especie', to='urts.urts')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_ciclo_especie_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_ciclo_especie_registro', to='usuarios.usuarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetais',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetais',
            name='del_usuario',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetais',
            name='urt',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetais',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetais',
            name='usuario_registro',
        ),
        migrations.DeleteModel(
            name='CicloEspeciesAnimais',
        ),
        migrations.DeleteModel(
            name='CicloEspeciesVegetais',
        ),
    ]
