# Generated by Django 4.2.5 on 2024-01-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0003_alter_urtespecievegetal_area_utilizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urtespecieanimal',
            name='area_utilizada',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
