# Generated by Django 4.2.5 on 2024-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0004_cicloespeciesvegetaisanimais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicloespeciesvegetaisanimais',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetaisanimais',
            name='del_usuario',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetaisanimais',
            name='urt',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetaisanimais',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cicloespeciesvegetaisanimais',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='cicloperiodosclimaticos',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='cicloperiodosclimaticos',
            name='del_usuario',
        ),
        migrations.RemoveField(
            model_name='cicloperiodosclimaticos',
            name='urt',
        ),
        migrations.RemoveField(
            model_name='cicloperiodosclimaticos',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='cicloperiodosclimaticos',
            name='usuario_registro',
        ),
        migrations.RenameField(
            model_name='ciclo',
            old_name='registro_data',
            new_name='registro_ddata_ata',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='status_ciclo',
            field=models.CharField(choices=[('nao_informado', 'Não informado'), ('em_preparacao', 'Em preparação'), ('em_execucao', 'Em execução'), ('suspenso', 'Suspenso'), ('cancelado', 'Encerrado')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CicloAtividades',
        ),
        migrations.DeleteModel(
            name='CicloEspeciesVegetaisAnimais',
        ),
        migrations.DeleteModel(
            name='CicloPeriodosClimaticos',
        ),
    ]
