# Generated by Django 4.2.5 on 2024-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0004_alter_urtespecieanimal_area_utilizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicourt',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='formacao_tecnica',
            field=models.CharField(choices=[('agronomia', 'Agronomia'), ('medicina_veterinaria', 'Medicina Veterinária'), ('zootecnia', 'Zootecnia'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], default='nao_informado', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='nome_fantasia',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='razao_social',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='status_contrato',
            field=models.CharField(choices=[('em_elaboracao', 'Em elaboração'), ('em_analise', 'Em análise'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('nao_informado', 'Não Informado')], default='nao_informado', max_length=20),
        ),
        migrations.AddField(
            model_name='tecnicourt',
            name='tecnico',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
    ]
