# Generated by Django 4.2.5 on 2024-01-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urts', '0005_tecnicourt_celular_tecnicourt_cnpj_tecnicourt_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicourt',
            name='urt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='urt_tecnico', to='urts.urts'),
            preserve_default=False,
        ),
    ]
