# Generated by Django 4.2.5 on 2024-01-23 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=15, null=True)),
                ('cor_pele', models.CharField(blank=True, choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=15, null=True)),
                ('foto_usuario', models.ImageField(blank=True, upload_to='fotos_usuarios/%Y/%m/%d/')),
                ('ramal', models.CharField(blank=True, max_length=4, null=True)),
                ('celular', models.CharField(blank=True, max_length=17, null=True)),
                ('email_institucional', models.EmailField(blank=True, max_length=40, null=True)),
                ('email_pessoal', models.EmailField(blank=True, max_length=40, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=150, null=True)),
                ('lattes', models.URLField(blank=True, max_length=150, null=True)),
                ('usuario_is_ativo', models.BooleanField(db_index=True, default=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_relacionado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alocacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('unidade', models.CharField(choices=[('', 'Não Informado'), ('dateg', 'DATeG'), ('icna', 'ICNA')], max_length=20)),
                ('setor', models.CharField(blank=True, max_length=60, null=True)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(db_index=True, default=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alocacao', to='usuarios.usuarios')),
            ],
        ),
    ]
