# Generated by Django 4.2.4 on 2023-09-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aloc_data_inicio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='aloc_setor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='aloc_unidade',
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('setor', models.CharField(blank=True, max_length=60, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(db_index=True, default=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alocacao', to='usuarios.usuario')),
            ],
        ),
    ]
