# Generated by Django 4.2.4 on 2023-09-06 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_aloc_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='unidade',
            field=models.CharField(choices=[('', '--- Selecione ---'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], default='gabinete', max_length=20),
        ),
    ]
