# Generated by Django 4.2.5 on 2023-09-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_alocacao_data_inicio_alter_alocacao_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cad_unidade_daf_info',
            field=models.CharField(choices=[('', '--- Selecione ---'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], default='gabinete', max_length=20),
            preserve_default=False,
        ),
    ]
