# Generated by Django 4.2.5 on 2023-09-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_cad_unidade_daf_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_is_ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
