# Generated by Django 4.2.5 on 2023-09-08 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_usuario_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='unidade',
            field=models.CharField(choices=[('', '--- Selecione ---'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alocacao', to='usuarios.usuario'),
        ),
    ]
