# Generated by Django 4.2.5 on 2023-09-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_alocacao_unidade_alter_alocacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cad_unidade_daf_info',
            field=models.CharField(blank=True, choices=[('', '--- Selecione ---'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], max_length=20, null=True),
        ),
    ]
