# Generated by Django 4.2.5 on 2023-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='unidade',
            field=models.CharField(choices=[('', 'Não Informado'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cad_unidade_daf_info',
            field=models.CharField(blank=True, choices=[('', 'Não Informado'), ('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE')], max_length=20, null=True),
        ),
    ]
