# Generated by Django 4.2.5 on 2023-12-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_alocacao_unidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ctt_celular',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dp_cor_pele',
            new_name='cor_pele',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dp_cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dp_data_nascimento',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ctt_email_ms',
            new_name='email_institucional',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ctt_email_pessoal',
            new_name='email_pessoal',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dp_genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rs_lattes',
            new_name='lattes',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rs_linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dp_nome_completo',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ctt_ramal_ms',
            new_name='ramal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cad_unidade_daf_info',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vms_orgao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vms_orgao_outro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vms_vinculo',
        ),
    ]
