# Generated by Django 4.2.5 on 2023-12-03 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedores', '0039_alter_fornecedores_hierarquia_and_more'),
        ('processos_aquisitivos', '0015_proaqtramitacao'),
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('main', '0006_customlog_model_customlog_model_id'),
        ('contratos', '0007_alter_contratos_arp'),
        ('usuarios', '0009_rename_ctt_celular_usuario_celular_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alocacao',
            new_name='Alocacoes',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
