# Generated by Django 4.2.5 on 2023-10-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNPJ_CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('secao_codigo', models.CharField(max_length=10)),
                ('secao_descricao', models.CharField(max_length=100)),
                ('divisao_codigo', models.CharField(max_length=20)),
                ('divisao_descricao', models.CharField(max_length=100)),
                ('grupo_codigo', models.CharField(max_length=20)),
                ('grupo_descricao', models.CharField(max_length=100)),
                ('classe_codigo', models.CharField(max_length=20)),
                ('classe_descricao', models.CharField(max_length=100)),
                ('subclasse_codigo', models.CharField(max_length=20)),
                ('subclasse_descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
