# Generated by Django 4.2.5 on 2023-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNPJ_NATUREZA_JURIDICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
                ('natureza_juridica', models.CharField(max_length=100)),
                ('representante_entidade', models.CharField(max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
            ],
        ),
    ]
