# Generated by Django 4.2.5 on 2023-10-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('fornecedores', '0003_uf_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('cnpj', models.CharField(max_length=18)),
                ('hierarquia', models.CharField(choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10)),
                ('porte', models.CharField(choices=[('me', 'ME'), ('medio_porte', 'Médio Porte'), ('epp', 'EPP'), ('demais', 'Demais'), ('mei', 'MEI'), ('grande_empresa', 'Grande Empresa')], max_length=20)),
                ('tipo_direito', models.CharField(blank=True, choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=10, null=True)),
                ('data_abertura', models.DateField()),
                ('natjuridica_codigo', models.CharField(max_length=10)),
                ('natjuridica_descricao', models.CharField(max_length=100)),
                ('ativ_principal_cod', models.CharField(max_length=20)),
                ('ativ_principal_descricao', models.CharField(max_length=200)),
                ('end_cep', models.CharField(max_length=10)),
                ('end_uf', models.CharField(max_length=2)),
                ('end_municipio', models.CharField(max_length=100)),
                ('end_logradouro', models.CharField(max_length=100)),
                ('end_numero', models.CharField(max_length=10)),
                ('end_bairro', models.CharField(max_length=100)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_registro', to='usuarios.usuario')),
            ],
        ),
    ]
