# Generated by Django 4.2.5 on 2023-10-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_fornecedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='nome_fantasia',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='razao_social',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('epp', 'EPP'), ('me', 'ME'), ('medio_porte', 'Médio Porte'), ('grande_empresa', 'Grande Empresa'), ('mei', 'MEI')], max_length=20),
        ),
    ]
