# Generated by Django 4.2.5 on 2023-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0005_fornecedores_nome_fantasia_fornecedores_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('mei', 'MEI'), ('demais', 'Demais'), ('me', 'ME'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
