# Generated by Django 4.2.5 on 2023-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0006_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='ativ_principal_cod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='ativ_principal_descricao',
            field=models.CharField(blank=True, default='Não informado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='end_bairro',
            field=models.CharField(blank=True, default='Não informado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='end_cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='end_logradouro',
            field=models.CharField(blank=True, default='Não informado', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='end_numero',
            field=models.CharField(blank=True, default='NI', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='natjuridica_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='natjuridica_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='Não informado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='observacoes_gerais',
            field=models.TextField(blank=True, default='Sem observações.', null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('mei', 'MEI'), ('medio_porte', 'Médio Porte'), ('me', 'ME')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('privado', 'Privado'), ('público', 'Público')], default='privado', max_length=10),
        ),
    ]
