# Generated by Django 4.2.5 on 2023-10-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0007_alter_fornecedores_ativ_principal_cod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('epp', 'EPP'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('me', 'ME')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('público', 'Público'), ('privado', 'Privado')], default='privado', max_length=10),
        ),
    ]
