# Generated by Django 4.2.5 on 2023-11-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('fornecedores', '0012_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('me', 'ME'), ('epp', 'EPP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('público', 'Público'), ('privado', 'Privado')], default='privado', max_length=10),
        ),
        migrations.CreateModel(
            name='Fornecedores_Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('topico', models.CharField(max_length=30)),
                ('topico_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('contexto', models.TextField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_faq_deletado', to='usuarios.usuario')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_faq_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_faq_registro', to='usuarios.usuario')),
            ],
        ),
    ]
