# Generated by Django 4.2.5 on 2023-11-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('fornecedores', '0013_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('epp', 'EPP'), ('me', 'ME'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('mei', 'MEI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('privado', 'Privado'), ('público', 'Público')], default='privado', max_length=10),
        ),
        migrations.AlterField(
            model_name='fornecedores_faq',
            name='topico',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('entrega_produto', 'Entrega de Produto Farmacêutico'), ('nota_fiscal', 'Nota Fiscal'), ('pregao', 'Pregão Eletrônico'), ('processo_incorporacao', 'Processo de Incorporação'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.CreateModel(
            name='Fornecedores_Representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero_sexual', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('representante_comercial', 'Representante Comercial'), ('assessor_tecnico', 'Assessor Técnico'), ('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('diretor', 'Diretor'), ('vice_presidente', 'Vice-Presidente'), ('presidente', 'Presidente'), ('outro', 'Outro')], max_length=30, null=True)),
                ('cargo_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_representante_deletado', to='usuarios.usuario')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_representante', to='fornecedores.fornecedores')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_representante_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_representante_registro', to='usuarios.usuario')),
            ],
        ),
    ]
