# Generated by Django 4.2.5 on 2023-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0014_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('medio_porte', 'Médio Porte'), ('grande_empresa', 'Grande Empresa'), ('mei', 'MEI'), ('epp', 'EPP'), ('me', 'ME')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores_representantes',
            name='cargo',
            field=models.CharField(blank=True, choices=[('representante_comercial', 'Representante Comercial'), ('assessor_tecnico', 'Assessor Técnico'), ('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('diretor', 'Diretor'), ('vice_presidente', 'Vice-Presidente'), ('presidente', 'Presidente'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores_representantes',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
