# Generated by Django 4.2.5 on 2023-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('fornecedores', '0018_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('me', 'ME'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores_comunicacoes',
            name='responsavel_resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_comunicacao_responsavel', to='usuarios.usuario'),
        ),
    ]
