# Generated by Django 4.2.5 on 2023-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0020_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('mei', 'MEI'), ('epp', 'EPP'), ('me', 'ME'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
