# Generated by Django 4.2.5 on 2023-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0021_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnpj_cnae',
            name='classe_descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cnpj_cnae',
            name='divisao_descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cnpj_cnae',
            name='grupo_descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cnpj_cnae',
            name='secao_descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cnpj_cnae',
            name='subclasse_descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('me', 'ME'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('mei', 'MEI'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('privado', 'Privado'), ('público', 'Público')], default='privado', max_length=10),
        ),
    ]
