# Generated by Django 4.2.5 on 2023-11-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0023_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('me', 'ME'), ('grande_empresa', 'Grande Empresa'), ('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('demais', 'Demais')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_direito',
            field=models.CharField(choices=[('público', 'Público'), ('privado', 'Privado')], default='privado', max_length=10),
        ),
    ]
