# Generated by Django 4.2.5 on 2023-11-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0025_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('mei', 'MEI'), ('me', 'ME'), ('medio_porte', 'Médio Porte'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('epp', 'EPP')], max_length=20),
        ),
    ]
