# Generated by Django 4.2.5 on 2023-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0027_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('me', 'ME'), ('demais', 'Demais'), ('epp', 'EPP'), ('mei', 'MEI'), ('grande_empresa', 'Grande Empresa')], max_length=20),
        ),
    ]
