# Generated by Django 4.2.5 on 2023-11-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0031_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('mei', 'MEI'), ('demais', 'Demais'), ('epp', 'EPP'), ('medio_porte', 'Médio Porte'), ('me', 'ME'), ('grande_empresa', 'Grande Empresa')], max_length=20),
        ),
    ]
