# Generated by Django 4.2.5 on 2023-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0036_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('epp', 'EPP'), ('me', 'ME'), ('mei', 'MEI'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
