# Generated by Django 4.2.5 on 2023-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0037_alter_fornecedores_porte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='hierarquia',
            field=models.CharField(blank=True, choices=[('filial', 'Filial'), ('matriz', 'Matriz')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('me', 'ME'), ('medio_porte', 'Médio Porte'), ('demais', 'Demais'), ('grande_empresa', 'Grande Empresa'), ('mei', 'MEI'), ('epp', 'EPP')], max_length=20),
        ),
    ]
