# Generated by Django 4.2.5 on 2023-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0042_alter_fornecedores_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('medio_porte', 'Médio Porte'), ('mei', 'MEI'), ('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('me', 'ME')], max_length=20),
        ),
    ]
