# Generated by Django 4.2.5 on 2023-12-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0046_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('grande_empresa', 'Grande Empresa'), ('epp', 'EPP'), ('me', 'ME'), ('mei', 'MEI'), ('demais', 'Demais'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
