# Generated by Django 4.2.5 on 2023-12-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0048_alter_fornecedores_hierarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='porte',
            field=models.CharField(choices=[('epp', 'EPP'), ('grande_empresa', 'Grande Empresa'), ('demais', 'Demais'), ('me', 'ME'), ('mei', 'MEI'), ('medio_porte', 'Médio Porte')], max_length=20),
        ),
    ]
