# Generated by Django 4.2.5 on 2023-12-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0011_alter_alocacoes_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('id_projeto_sisateg', models.CharField(blank=True, max_length=40, null=True)),
                ('regional', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
                ('regiao', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('em_elaboracao', 'Em Elaboração'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], max_length=20)),
                ('nome_plano_trabalho', models.TextField()),
                ('n_processo', models.CharField(blank=True, max_length=40, null=True)),
                ('termo_adesao', models.CharField(blank=True, max_length=40, null=True)),
                ('n_plano_trabalho', models.CharField(blank=True, max_length=40, null=True)),
                ('n_reformulacoes', models.IntegerField(default=0)),
                ('n_docs', models.CharField(blank=True, max_length=40, null=True)),
                ('n_aviso_encerramento', models.CharField(blank=True, max_length=40, null=True)),
                ('n_prestacao_contas', models.CharField(blank=True, max_length=40, null=True)),
                ('subprograma', models.TextField(blank=True, null=True)),
                ('geracao_projeto', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('n_tecnicos', models.IntegerField(default=0)),
                ('n_supervisores', models.IntegerField(default=0)),
                ('n_tecnicos_supervisores_ead', models.IntegerField(default=0)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_deletado', to='usuarios.usuarios')),
                ('gestor_dateg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_gestor', to='usuarios.usuarios')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_registro', to='usuarios.usuarios')),
            ],
        ),
    ]
