# Generated by Django 4.2.5 on 2023-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='n_prestacao_contas',
            field=models.CharField(blank=True, choices=[('agronordeste2', 'Agronordeste 2'), ('cadeias_produtivas', 'Cadeias Produtivas'), ('expansao_ateg', 'Expansão ATeG'), ('expansao_ateg_2_1', 'Expansão ATeG 2-1'), ('especiais_diretoria', 'Especiais Diretoria')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='observacoes_gerais',
            field=models.TextField(blank=True, default='Sem observações.', null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='regional',
            field=models.CharField(choices=[('ac', 'AC'), ('al', 'AL'), ('am', 'AM'), ('ap', 'AP'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('ro', 'RO'), ('rr', 'RR'), ('rs', 'RS'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2),
        ),
    ]
