# Generated by Django 4.2.5 on 2023-12-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projetos_n_prestacao_contas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='regiao',
        ),
    ]
