# Generated by Django 4.2.5 on 2023-12-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_projetos_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='n_reformulacoes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
