# Generated by Django 4.2.5 on 2023-12-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_alocacoes_unidade'),
        ('projetos', '0004_alter_projetos_n_reformulacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='n_supervisores',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='n_tecnicos',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='n_tecnicos_supervisores_ead',
        ),
        migrations.AlterField(
            model_name='projetos',
            name='n_prestacao_contas',
            field=models.CharField(blank=True, choices=[('', ''), ('agronordeste2', 'Agronordeste 2'), ('cadeias_produtivas', 'Cadeias Produtivas'), ('expansao_ateg', 'Expansão ATeG'), ('expansao_ateg_2_1', 'Expansão ATeG 2-1'), ('especiais_diretoria', 'Especiais Diretoria')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='regional',
            field=models.CharField(choices=[('', ''), ('ac', 'AC'), ('al', 'AL'), ('am', 'AM'), ('ap', 'AP'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pe', 'PE'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('ro', 'RO'), ('rr', 'RR'), ('rs', 'RS'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='status',
            field=models.CharField(choices=[('', ''), ('em_elaboracao', 'Em Elaboração'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='subprograma',
            field=models.TextField(blank=True, choices=[('', ''), ('agronordeste2', 'Agronordeste 2'), ('cadeias_produtivas', 'Cadeias Produtivas'), ('expansao_ateg', 'Expansão ATeG'), ('expansao_ateg_2_1', 'Expansão ATeG 2-1'), ('especiais_diretoria', 'Especiais Diretoria')], null=True),
        ),
        migrations.CreateModel(
            name='ProjetosAtividadesProdutivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('atividade', models.IntegerField(choices=[(12, 'Agricultura Anual'), (15, 'Agricultura Orgânica'), (23, 'Agroindústria da Cana de Acúcar'), (37, 'Agroindústria de Azeite de Oliva'), (38, 'Agroindústria de Cera'), (25, 'Agroindústria de Derivados Lácteos'), (31, 'Agroindústria de Derivados Vegetais'), (35, 'Agroindústria de Farinha e Mandioca'), (41, 'Agroindústria de Ovos'), (36, 'Agroindústria de Panificação'), (33, 'Agroindústria de Pescado'), (34, 'Agroindústria de Polpas e Bebidas'), (39, 'Agroindústria de Produtos Apícola'), (26, 'Agroindústria de Embutidos, Defumados e Processo de Carnes'), (30, 'Agroindústria de Lácetos'), (8, 'Apicultura'), (10, 'Avicultura'), (2, 'Bovinocultura de Corte'), (1, 'Bovinocultura de Leite'), (14, 'Cacauicultura'), (3, 'Cafeicultura'), (20, 'Cana de Açúcar'), (19, 'Carcinicultura'), (28, 'Equideocultura'), (13, 'Floresta'), (17, 'Floricultura'), (4, 'Fruticultura Perene'), (27, 'Heveicultura'), (11, 'Maricultura'), (21, 'Minhocultura'), (7, 'Olericultura'), (6, 'Ovinocaprinocultura de Corte'), (5, 'Ovinocaprinocultura de Leite'), (29, 'Pipericultura'), (9, 'Piscicultura'), (42, 'Silvicultura'), (24, 'Sisalicultura'), (32, 'Sistemas Integrados de Produção'), (18, 'Suinocultura')])),
                ('n_propriedades', models.IntegerField(default=0)),
                ('n_cadernos', models.IntegerField(default=0)),
                ('n_tecnicos', models.IntegerField(default=0)),
                ('n_supervisores', models.IntegerField(default=0)),
                ('n_tecnicos_supervisores_ead', models.IntegerField(default=0)),
                ('observacoes_gerais', models.TextField(blank=True, default='Sem observações.', null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_atividade_deletado', to='usuarios.usuarios')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto_atividade_produtiva', to='projetos.projetos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_atividade_edicao', to='usuarios.usuarios')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_projeto_atividade_registro', to='usuarios.usuarios')),
            ],
        ),
    ]
