# Generated by Django 4.2.5 on 2023-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_remove_projetos_n_supervisores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='n_prestacao_contas',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='projetosatividadesprodutivas',
            name='atividade',
            field=models.IntegerField(choices=[('', ''), (12, 'Agricultura Anual'), (15, 'Agricultura Orgânica'), (23, 'Agroindústria da Cana de Acúcar'), (37, 'Agroindústria de Azeite de Oliva'), (38, 'Agroindústria de Cera'), (25, 'Agroindústria de Derivados Lácteos'), (31, 'Agroindústria de Derivados Vegetais'), (35, 'Agroindústria de Farinha e Mandioca'), (41, 'Agroindústria de Ovos'), (36, 'Agroindústria de Panificação'), (33, 'Agroindústria de Pescado'), (34, 'Agroindústria de Polpas e Bebidas'), (39, 'Agroindústria de Produtos Apícola'), (26, 'Agroindústria de Embutidos, Defumados e Processo de Carnes'), (30, 'Agroindústria de Lácetos'), (8, 'Apicultura'), (10, 'Avicultura'), (2, 'Bovinocultura de Corte'), (1, 'Bovinocultura de Leite'), (14, 'Cacauicultura'), (3, 'Cafeicultura'), (20, 'Cana de Açúcar'), (19, 'Carcinicultura'), (28, 'Equideocultura'), (13, 'Floresta'), (17, 'Floricultura'), (4, 'Fruticultura Perene'), (27, 'Heveicultura'), (11, 'Maricultura'), (21, 'Minhocultura'), (7, 'Olericultura'), (6, 'Ovinocaprinocultura de Corte'), (5, 'Ovinocaprinocultura de Leite'), (29, 'Pipericultura'), (9, 'Piscicultura'), (42, 'Silvicultura'), (24, 'Sisalicultura'), (32, 'Sistemas Integrados de Produção'), (18, 'Suinocultura')]),
        ),
    ]
