# Generated by Django 4.2.4 on 2023-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vms_orgao',
            field=models.CharField(blank=True, choices=[('min_saude', 'Ministério da Saúde'), ('outro', 'Outro')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vms_orgao_outro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vms_vinculo',
            field=models.CharField(blank=True, choices=[('consultor', 'Consultor Técnico'), ('servidor_federal', 'Servidor Federal'), ('servidor_estadual', 'Servidor Estadual'), ('servidor_municipal', 'Servidor Municipal')], max_length=20, null=True),
        ),
    ]
