# Generated by Django 4.2.4 on 2023-09-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario_vms_orgao_usuario_vms_orgao_outro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aloc_data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aloc_setor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aloc_unidade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dp_cor_pele',
            field=models.CharField(blank=True, choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vms_orgao',
            field=models.CharField(blank=True, choices=[('min_saude', 'Ministério da Saúde'), ('outro', 'Outro'), ('nao_informado', 'Não Informado')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vms_vinculo',
            field=models.CharField(blank=True, choices=[('consultor', 'Consultor Técnico'), ('servidor_federal', 'Servidor Federal'), ('servidor_estadual', 'Servidor Estadual'), ('servidor_municipal', 'Servidor Municipal'), ('nao_informado', 'Não Informado')], max_length=20, null=True),
        ),
    ]
