# Generated by Django 4.2.4 on 2023-09-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuario_aloc_data_inicio_usuario_aloc_setor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
