# Generated by Django 4.2.5 on 2023-09-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('main', '0004_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acesso_usuario', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CustomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(max_length=140)),
                ('item_id', models.IntegerField()),
                ('item_descricao', models.CharField(max_length=140)),
                ('acao', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=40)),
                ('observacoes', models.CharField(default='Sem observações.', max_length=240)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
