# Generated by Django 4.2.5 on 2023-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlog',
            name='model',
            field=models.CharField(default='Não informado', max_length=60),
        ),
        migrations.AddField(
            model_name='customlog',
            name='model_id',
            field=models.IntegerField(default=0),
        ),
    ]
