# Generated by Django 4.2.5 on 2023-11-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0023_alter_fornecedores_porte'),
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('produtos', '0018_alter_produtosfarmaceuticos_concentracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratosArps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('unidade_daf', models.TextField(choices=[('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE'), ('nao_informado', 'Não Informado')], max_length=15)),
                ('numero_processo_sei', models.TextField(max_length=20)),
                ('numero_documento_sei', models.TextField(max_length=10)),
                ('numero_arp', models.TextField(max_length=15)),
                ('status', models.CharField(choices=[('nao_publicado', 'Não Publicado'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado')], default='nao_informado', max_length=20)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_deletado', to='usuarios.usuario')),
                ('denominacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacao_arp', to='produtos.denominacoesgenericas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_arp', to='fornecedores.fornecedores')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_registro', to='usuarios.usuario')),
            ],
        ),
    ]
