# Generated by Django 4.2.5 on 2023-11-23 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosarps',
            name='status',
            field=models.CharField(choices=[('nao_publicado', 'Não Publicado'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado'), ('', 'Não Informado')], default='nao_informado', max_length=20),
        ),
        migrations.CreateModel(
            name='ContratosArpsItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('numero_item', models.IntegerField()),
                ('tipo_cota', models.CharField(choices=[('principal', 'Principal'), ('reservada', 'Reservada')], max_length=20)),
                ('empate_ficto', models.BooleanField()),
                ('valor_unit_homologado', models.FloatField()),
                ('valor_unit_reequilibrio_bool', models.BooleanField(default=False)),
                ('valor_unit_reequilibrio', models.FloatField(blank=True, null=True)),
                ('qtd_registrada', models.FloatField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('arp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item', to='contratos.contratosarps')),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_deletado', to='usuarios.usuario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_produto', to='produtos.produtosfarmaceuticos')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_item_registro', to='usuarios.usuario')),
            ],
        ),
    ]
