# Generated by Django 4.2.5 on 2023-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contratosarps_status_contratosarpsitens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosarps',
            name='status',
            field=models.CharField(choices=[('nao_publicado', 'Não Publicado'), ('vigente', 'Vigente'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado'), ('', 'Não Informado')], default='nao_informado', max_length=20),
        ),
    ]
