# Generated by Django 4.2.5 on 2023-11-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0029_alter_fornecedores_porte'),
        ('produtos', '0020_produtoconsumomedio_aprovado_total'),
        ('usuarios', '0007_alter_usuario_cad_unidade_daf_info'),
        ('contratos', '0003_alter_contratosarps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosarps',
            name='status',
            field=models.CharField(choices=[('nao_publicado', 'Não Publicado'), ('vigente', 'Vigente'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('', 'Não Informado')], default='nao_informado', max_length=20),
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_data', models.DateTimeField(auto_now_add=True)),
                ('ult_atual_data', models.DateTimeField(auto_now=True)),
                ('log_n_edicoes', models.IntegerField(default=1)),
                ('unidade_daf', models.TextField(choices=[('cgafb', 'CGAFB'), ('cgafme', 'CGAFME'), ('cgceaf', 'CGCEAF'), ('cgfp', 'CGFP'), ('cofisc', 'COFISC'), ('gabinete', 'GABINETE'), ('nao_informado', 'Não Informado')], max_length=15)),
                ('numero_processo_sei', models.TextField(max_length=20)),
                ('numero_documento_sei', models.TextField(max_length=10)),
                ('numero_contrato', models.TextField(max_length=15)),
                ('status', models.CharField(choices=[('nao_publicado', 'Não Publicado'), ('vigente', 'Vigente'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('', 'Não Informado')], default='nao_informado', max_length=20)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('arp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_contrato', to='contratos.contratosarps')),
                ('del_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_deletado', to='usuarios.usuario')),
                ('denominacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='denominacao_contrato', to='produtos.denominacoesgenericas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor_contrato', to='fornecedores.fornecedores')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_edicao', to='usuarios.usuario')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contrato_registro', to='usuarios.usuario')),
            ],
        ),
    ]
