# Generated by Django 4.2.5 on 2023-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contratosarps_status_contratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='modalidade_aquisicao',
            field=models.TextField(choices=[('emergencial', 'Emergencial'), ('inexigibilidade', 'Inexigibilidade'), ('pregao_comarp', 'Pregão Com ARP'), ('pregao_semarp', 'Pregão Sem ARP')], default='nao_informado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero_documento_sei',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero_processo_sei',
            field=models.CharField(max_length=20),
        ),
    ]
