# Generated by Django 4.2.5 on 2023-12-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contratos_lei_licitacao_contratosarps_lei_licitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='arp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='arp_contrato', to='contratos.contratosarps'),
        ),
    ]
